name: CI

on:
  # Trigger when pushing to any branch
  push:
    branches:
      - main

  # Trigger on pull requests to any branch
  pull_request:

  # Run periodically using cron (UTC time)
  schedule:
    - cron: '16 0 * * *'  # Every day at 00:00 UTC

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: run test script
      run: |
        set -ex
        pip install --upgrade pip
        pip install poetry
        poetry install
        echo "${{ secrets.PIKPAK_ENV }}" > tests/.env
        ls -alht tests/
        test_log=test.$(date +'%Y%m%dT%H%M%S').log
        poetry run ./run_tests.sh
