name: CI

on:
  # Trigger when pushing to any branch
  push:
    - main

  # Trigger on pull requests to any branch
  pull_request:

  # Run periodically using cron (UTC time)
  schedule:
    - cron: '16 0 * * *'  # Every day at 00:00 UTC

permissions:
  contents: read

jobs:
  ci:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9, 3.12, 3.14]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: run test script
      run: |
        apt update && apt upgrade -y
        apt install poetry
        poetry install
        ./run_tests.py
